apiVersion: v1
kind: Service
metadata:
  name: service-2048
spec:
  type: NodePort
  selector:
    app: 2048-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
